---
version: '2'
services:
  exchange:
    extends:
      file: common.yml
      service: exchange
    ports:
    - 8080:8080
    environment:
    - RAILS_ENV=test
    - DATABASE_HOST=exchange-db
    - DATABASE_USER=postgres
    - REDIS_URL=redis://exchange-redis

    - CI
    - CIRCLECI
    - CIRCLE_BRANCH
    - CIRCLE_BUILD_NUM
    - CIRCLE_NODE_INDEX
    - CIRCLE_NODE_TOTAL
    - CIRCLE_SHA1
    - CI_PULL_REQUEST
    - COVERALLS_REPO_TOKEN
    - DANGER_GITHUB_API_TOKEN
    command: ./hokusai/ci.sh
    depends_on:
      - exchange-db
      - exchange-redis
    volumes:
      - "../.git:/app/.git:ro"
  exchange-db:
    image: postgres:9.6-alpine
  exchange-redis:
    image: redis:3.2-alpine
